### ISSUE TITLE
Does this package modify UEFI data?

### ISSUE THREAD

**Issue by etoyz** [linux-surface/secureboot-mok#2]
For some reason, my system malfunctioned, and when I tried to reinstall it, the screen output:

> Failed to open \EFI\BOOT\mmx64.efi - Not Found
> Failed to load image: Not Found
> Failed to start MokManager: Not Found
> Something has gone seriously wrong: import_mok_state(): Not Found

It looks like the UEFI try to find MokManager?

**Comment by qzed** [comment]
The secureboot keys are stored in memory that is only accessible through UEFI. MokManager is the EFI executable that allows you to manage those keys (i.e. add and remove them).

When you install this package, it runs `mokutil`, which prepares the addition of the Surface secureboot key. It cannot, however, directly add those keys. Instead it instructs Shim (which is essentially an EFI boot stub for secureboot that checks and validates any subsequent executables/kernels) to execute MokManager and tells that to add the Surface key.

So here it looks like Shim can't find MokManager. Which means something with your secureboot setup is broken.

It might also be possible that you're booting into the wrong boot entry. You could check if you can find `EFI/<dir>/mmx64.efi` for some `<dir>` on your EFI partition (that's usually mounted at `/boot/efi` or just `/efi` (so something like `/boot/efi/EFI/Fedora/mmx64.efi` for Fedora, I believe). Then check if you have that in your UEFI boot menu and try to boot that.

**Comment by etoyz** [comment]
@qzed 
Thanks for your reply.

I have tried a fresh installation of Debian12 and the latest official image of Debian12 does not seem to contain /EFI/boot/mmx64.efi. I have also tried formatting the computer hard drive and recreating the installation media to get back to my first installation state, but this didn't work because it said it couldn't find MokManager. How do I get back to the original state, in other words, how do I get “shim” to stop searching for MokManager?

**Comment by qzed** [comment]
Generally, distributions install their bootloader to `/EFI/<distribution>`, so check `/EFI/Debian` in your case. And make sure that you have that selected as first entry in the UEFI boot options menu.

**Comment by etoyz** [comment]
I've reset surface's UEFI with the following steps, and the 'shim' doesn't try to find the MokManager on boot anymore
1. [Create a bootable USB media to access UEFI shell](https://kcm.trellix.com/corporate/index?page=content&id=KB90801&locale=en_US)
3. Boot to UEFI shell from USB
4. Enter the following command to delete all var starting with "Mok" 
`dmpstore -d -all Mok*`
5. Reinstall the OS you need.
